[window]
width = 1000
height = 1000
title = "Vulkan MIDI Pixel Shader"
fullscreen = false
resizable = true

[midi]
enabled = true
auto_connect = true
#port_name = "ESI MIDIMATE eX:ESI MIDIMATE eX MIDI 2 24:1"
port_name = "MPK261"

[graphics]
vsync = true
validation_layers = true

[audio]
enabled = true

[shader]
#preset = "torus"
#preset = "terrain"
#preset = "crystal"
#preset = "weirdcrystal"
#preset = "custom"
#preset = "stars"
#preset = "computeparticles"
#custom_vertex_path = "shaders/custom.vert"
#custom_fragment_path = "shaders/custom.frag"
allow_runtime_switching = false

[osc]
enabled = true
port = 7001
address = "0.0.0.0"  #