[window]
width = 1000
height = 1000
title = "Vulkan MIDI Pixel Shader"
fullscreen = false
resizable = true

[midi]
enabled = true
auto_connect = true
#port_name = "ESI MIDIMATE eX:ESI MIDIMATE eX MIDI 2 24:1"
port_name = "MPK261"

[graphics]
vsync = true
validation_layers = true

[audio]
enabled = true
device_name = "CABLE Output (2- VB-Audio Virtual Cable)"

[shader]
active_preset = "new"
allow_runtime_switching = true

[shader.presets.new]
name = "New Fullscreen"
enabled = true
geometry_type = "fullscreen"
vertex = "fullscreen.vert"
fragment = "wildbeauty.frag"

[shader.presets.new2]
name = "New Fullscreen2"
enabled = true
geometry_type = "fullscreen"
vertex = "fullscreen.vert"
fragment = "wildbeauty2.frag"

[shader.presets.torus]
name = "Torus Fullscreen"
enabled = true
geometry_type = "fullscreen"
vertex = "fullscreen.vert"
fragment = "cloud3.frag"

[shader.presets.terrain]
name = "Terrain"
enabled = false # crashes
geometry_type = "vertices"
vertex = "terrain.vert"
fragment = "terrain.frag"

[shader.presets.crystal]
name = "Simple Crystal"
enabled = true
geometry_type = "points"
vertex = "points.vert"
geometry = "simple.geom"
fragment = "simple_geometry.frag"

[shader.presets.weirdcrystal]
name = "Complex Crystal"
enabled = true
geometry_type = "points"
vertex = "points.vert"
geometry = "example.geom"
fragment = "stars.frag"

[shader.presets.stars]
name = "Stars"
enabled = true
geometry_type = "vertices"
vertex = "fullscreen.vert"
fragment = "stars.frag"

[shader.presets.computeparticles]
name = "Compute Particles"
enabled = false
geometry_type = "compute"
vertex = "instanced_triangles.vert"
fragment = "instanced_triangles.frag"
compute = "point_generator.comp"

[osc]
enabled = true
port = 7001
address = "0.0.0.0"  #