pub mod vulkan;
pub mod shaders;
pub mod egui_overlay;

// Re-export Vulkan types for convenience
pub use vulkan::{VulkanContext, VulkanSwapchain, VulkanBuffers};
pub use shaders::ShaderSources;

// Geometry types
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum GeometryMode {
    Trivial,           // Simple fullscreen quad for fragment-only shaders
    InstancedTriangles, // Complex instanced triangle rendering
    GeometryShader,    // Points expanded by geometry shader
    ComputeGenerated,  // Points generated by compute shader
}

// Core vertex structures
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Vertex {
    pub pos: [f32; 2],
    pub uv: [f32; 2],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct InstanceData {
    pub offset: [f32; 2],
    pub scale: [f32; 2],
    pub rotation_cos: f32,
    pub rotation_sin: f32,
    pub color_index: u32,
    pub _padding: u32,
}

// Push constants structure - must match shader layout
#[repr(C)]
#[derive(Clone, Copy)]
pub struct PushConstants {
    pub time: f32,
    pub mouse_x: u32,
    pub mouse_y: u32,
    pub mouse_pressed: u32,
    pub note_velocity: f32,
    pub pitch_bend: f32,
    pub cc1: f32,
    pub cc74: f32,
    pub note_count: u32,
    pub last_note: u32,
    pub osc_ch1: f32,
    pub osc_ch2: f32,
    pub render_w: u32,
    pub render_h: u32,
    pub bpm: f32,
    pub time_to_next_beat: f32,
    pub time_since_last_beat: f32,
    pub beats_per_bar: u32,
    pub max_points: u32,
    pub fft_size: u32,
    pub audio_intensity: f32,
    pub bass_level: f32,
    pub mid_level: f32,
    pub high_level: f32,
}

// Point data structure matching the compute shader
#[repr(C)]
#[derive(Clone, Copy)]
pub struct PointData {
    pub position: [f32; 2],
    pub size: f32,
    pub intensity: f32,
    pub color: [f32; 4],
    pub rotation: f32,
    pub point_type: u32,
    pub velocity: [f32; 2],
}

impl PushConstants {
    pub fn from_frame(
        frame: &crate::state::FrameState,
        time: f32,
        mouse: (u32, u32, bool),
        size: (u32, u32),
    ) -> Self {
        let m = &frame.midi;
        let a = &frame.audio_levels;
        let b = &frame.beat;

        let note_velocity = if m.note_count > 0 { m.note_velocity } else { 0.0 };

        Self {
            time,
            mouse_x: mouse.0,
            mouse_y: mouse.1,
            mouse_pressed: mouse.2 as u32,
            note_velocity: note_velocity.max(a.level_rms),
            pitch_bend: m.pitch_bend.max(a.low * 2.0 - 1.0),
            cc1: m.cc1.max(a.mid),
            cc74: m.cc74.max(a.high),
            note_count: m.note_count,
            last_note: m.last_note as u32,
            osc_ch1: frame.osc.channel1,
            osc_ch2: frame.osc.channel2,
            render_w: size.0,
            render_h: size.1,
            bpm: b.bpm,
            time_to_next_beat: b.time_to_next_beat,
            time_since_last_beat: b.time_since_last_beat,
            beats_per_bar: b.beats_per_bar,
            max_points: 50000,
            fft_size: 1024,
            audio_intensity: a.level_rms,
            bass_level: a.low,
            mid_level: a.mid,
            high_level: a.high,
        }
    }
}

impl Default for PushConstants {
    fn default() -> Self {
        Self {
            time: 0.0,
            mouse_x: 0,
            mouse_y: 0,
            mouse_pressed: 0,
            note_velocity: 0.0,
            pitch_bend: 0.0,
            cc1: 0.0,
            cc74: 0.0,
            note_count: 0,
            last_note: 0,
            osc_ch1: 0.0,
            osc_ch2: 0.0,
            render_w: 1920,
            render_h: 1080,
            bpm: 0.0,
            time_to_next_beat: 0.0,
            time_since_last_beat: 0.0,
            beats_per_bar: 4,
            max_points: 1000,
            fft_size: 512,
            audio_intensity: 0.0,
            bass_level: 0.0,
            mid_level: 0.0,
            high_level: 0.0,
        }
    }
}