// Core graphics module - contains type definitions used by main.rs
// use anyhow::Result; // Unused
// use winit::window::Window; // Unused
// use crate::config::config::ShaderConfig; // Unused

pub mod vulkan;
pub mod shaders;
pub mod renderer;
pub mod overlay;

// pub use vulkan::{VulkanContext, VulkanSwapchain, VulkanBuffers, VulkanPipeline, VulkanCommands, VulkanSync}; // Temporarily disabled
// pub use renderer::Gfx; // Not yet extracted
// pub use shaders::ShaderSources; // Unused for now

// Re-export geometry types for convenience
#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum GeometryMode {
    Trivial,           // Simple fullscreen quad for fragment-only shaders
    InstancedTriangles, // Complex instanced triangle rendering
    GeometryShader,    // Points expanded by geometry shader
    ComputeGenerated,  // Points generated by compute shader
}

// Re-export core vertex structures
#[allow(dead_code)]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Vertex {
    pub pos: [f32; 2],
    pub uv: [f32; 2],
}

#[allow(dead_code)]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct InstanceData {
    pub offset: [f32; 2],
    pub scale: [f32; 2],
    pub rotation_cos: f32,    // Pre-computed cos
    pub rotation_sin: f32,    // Pre-computed sin
    pub color_index: u32,     // Back to u32 for alignment
    pub _padding: u32,        // Alignment padding
}

// Push constants structure
#[allow(dead_code)]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct PushConstants {
    pub time: f32,
    pub mouse_x: u32,
    pub mouse_y: u32,
    pub mouse_pressed: u32,
    pub note_velocity: f32,
    pub pitch_bend: f32,
    pub cc1: f32,
    pub cc74: f32,
    pub note_count: u32,
    pub last_note: u32,
    pub osc_ch1: f32,
    pub osc_ch2: f32,
    pub render_w: u32,
    pub render_h: u32,
    pub beat_intensity: f32,
    pub beat_pulse: f32,
    pub audio_energy: f32,
    pub audio_spectrum_low: f32,
    pub audio_spectrum_mid: f32,
    pub audio_spectrum_high: f32,
    pub _padding: [u32; 4], // Ensure 16-byte alignment
}

impl Default for PushConstants {
    fn default() -> Self {
        Self {
            time: 0.0,
            mouse_x: 0,
            mouse_y: 0,
            mouse_pressed: 0,
            note_velocity: 0.0,
            pitch_bend: 0.0,
            cc1: 0.0,
            cc74: 0.0,
            note_count: 0,
            last_note: 0,
            osc_ch1: 0.0,
            osc_ch2: 0.0,
            render_w: 1920,
            render_h: 1080,
            beat_intensity: 0.0,
            beat_pulse: 0.0,
            audio_energy: 0.0,
            audio_spectrum_low: 0.0,
            audio_spectrum_mid: 0.0,
            audio_spectrum_high: 0.0,
            _padding: [0; 4],
        }
    }
}