// Common types used across vulkan modules

// Geometry rendering modes
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum GeometryMode {
    Trivial,           // Simple fullscreen quad for fragment-only shaders
    InstancedTriangles, // Complex instanced triangle rendering
    GeometryShader,    // Points expanded by geometry shader
    ComputeGenerated,  // Points generated by compute shader
}

// vertex data structures
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Vertex {
    pub pos: [f32; 2],
    pub uv: [f32; 2],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct InstanceData {
    pub offset: [f32; 2],
    pub scale: [f32; 2],
    pub rotation_cos: f32,    // Pre-computed cos
    pub rotation_sin: f32,    // Pre-computed sin
    pub color_index: u32,     // Back to u32 for alignment
    pub _padding: u32,        // Alignment padding
}

// push constants
#[repr(C)]
#[derive(Clone, Copy)]
pub struct PushConstants {
    pub time: f32,
    pub mouse_x: u32,
    pub mouse_y: u32,
    pub mouse_pressed: u32,
    pub note_velocity: f32,
    pub pitch_bend: f32,
    pub cc1: f32,
    pub cc74: f32,
    pub note_count: u32,
    pub last_note: u32,
    pub osc_ch1: f32,
    pub osc_ch2: f32,
    pub render_w: u32,
    pub render_h: u32,
    pub bpm: f32,
    pub time_to_next_beat: f32,
    pub time_since_last_beat: f32,
    pub beats_per_bar: u32,
    pub max_points: u32,
    pub fft_size: u32,
    pub audio_intensity: f32,
    pub bass_level: f32,
    pub mid_level: f32,
    pub high_level: f32,
}

// Point data structure matching the compute shader
#[repr(C)]
#[derive(Clone, Copy)]
pub struct PointData {
    pub position: [f32; 2],
    pub size: f32,
    pub intensity: f32,
    pub color: [f32; 4],
    pub rotation: f32,
    pub point_type: u32,
    pub velocity: [f32; 2],
}